name: Backend CI/CD

on:
  push:
    branches:
      - master
      - dev
      - feature/**
      - fix/**
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        working-directory: ./backend
        run: composer install

      - name: Copy .env
        working-directory: ./backend
        run: cp .env.example .env

      - name: Generate APP_KEY
        working-directory: ./backend
        run: php artisan key:generate

      - name: Run migrations
        working-directory: ./backend
        run: php artisan migrate --force

      - name: Run tests
        working-directory: ./backend
        run: php artisan test
