name: Backend CI/CD

on:
  push:
    branches:
      - feature**
      - fix**
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        working-directory: ./backend
        run: composer install

      - name: Copy .env
        working-directory: ./backend
        run: cp .env.example .env

      - name: Generate APP_KEY
        working-directory: ./backend
        run: php artisan key:generate

      - name: Run migrations
        working-directory: ./backend
        run: php artisan migrate --force

      - name: Run tests
        working-directory: ./backend
        run: php artisan test

  create-pull-request:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.LARAVEL_GITHUB_ACTION_TEST }}
            commit-message: PR:Merge changes from feature/fix branch
            branch: master
            title: 'PR: Merge changes from feature/fix branch'
            body: |
              This pull request is automatically created from the successful test of feature/fix branch.
