name: Backend CI/CD

on:
  push:
    branches:
      - master
      - dev
      - feature**
      - fix**
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        working-directory: ./backend
        run: composer install

      - name: Copy .env
        working-directory: ./backend
        run: cp .env.example .env

      - name: Generate APP_KEY
        working-directory: ./backend
        run: php artisan key:generate

      - name: Run migrations
        working-directory: ./backend
        run: php artisan migrate --force

      - name: Run tests
        working-directory: ./backend
        run: php artisan test

  create-pull-request:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Make sure to fetch all history so we can push tags if needed

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.LARAVEL_GITHUB_ACTION_TEST }}
        run: |
          PR_COUNT=$(gh pr list --head "${{ github.ref_name }}" --json number --jq '. | length')
          if [[ $PR_COUNT == 0 ]]; then
            gh pr create \
              -B master \
              -t "${{ github.event.head_commit.message }}" \
              -a "${{ github.actor }}"  \
          else
            echo "PR already exists."
          fi

